# Generated by Django 4.2.6 on 2023-10-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorttermcourse',
            name='description',
            field=models.TextField(),
        ),
    ]
